version: 0.2

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - npm install
      - npm test
  build:
    commands:
      - npm run webpack
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - dist/bundle.js
    - favicon/*
    - src/assets/images/about/*
    - src/assets/images/landing/*
    - src/assets/images/skills/*
    - src/assets/images/work/*
    - AlbertoMarinGarciaResume.pdf
    - index.html